"""empty message

Revision ID: 08be3dc03508
Revises: 6ecdff2e21f1
Create Date: 2017-12-14 04:47:54.402995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08be3dc03508'
down_revision = '6ecdff2e21f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'att_employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('attendances', 'days_present',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('attendances', 'leave_days',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('attendances', 'percentage_attendance',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('employees', 'emp_number',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('employees', 'emp_project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('employees', 'emp_role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('employees', 'emp_subproject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('incentives', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('incentives', 'av_qa_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('incentives', 'inc_attendances_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('incentives', 'inc_employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('incentives', 'inc_subproject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('incentives', 'production',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('incentives', 'total_points',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('projects', 'pro_employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('subprojects', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('subprojects', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('subprojects', 'sp_project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subprojects', 'sp_project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('subprojects', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('subprojects', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('projects', 'pro_employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('incentives', 'total_points',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('incentives', 'production',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('incentives', 'inc_subproject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('incentives', 'inc_employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('incentives', 'inc_attendances_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('incentives', 'av_qa_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('incentives', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('employees', 'emp_subproject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('employees', 'emp_role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('employees', 'emp_project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('employees', 'emp_number',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('attendances', 'percentage_attendance',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('attendances', 'leave_days',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('attendances', 'days_present',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('attendances', 'att_employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
