"""empty message

Revision ID: 294a644ddaea
Revises: 949783cf43d6
Create Date: 2017-12-11 09:28:55.811142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294a644ddaea'
down_revision = '949783cf43d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subprojects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subprojects')
    # ### end Alembic commands ###
