"""empty message

Revision ID: 2c8288009690
Revises: 294a644ddaea
Create Date: 2017-12-11 09:32:28.417204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8288009690'
down_revision = '294a644ddaea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_number', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('emp_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_emp_name'), 'employees', ['emp_name'], unique=False)
    op.create_index(op.f('ix_employees_emp_number'), 'employees', ['emp_number'], unique=True)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
