"""empty message

Revision ID: 4895dc4a3dc0
Revises: 6d4db65d9acd
Create Date: 2017-12-16 09:33:45.497928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4895dc4a3dc0'
down_revision = '6d4db65d9acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emp_project_id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('emp_subproject_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'employees_ibfk_3', 'employees', type_='foreignkey')
    op.drop_constraint(u'employees_ibfk_4', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'projects', ['emp_project_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'subprojects', ['emp_subproject_id'], ['id'])
    op.drop_column('employees', 'project')
    op.drop_column('employees', 'subproject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('subproject', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('project', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(u'employees_ibfk_4', 'employees', 'subprojects', ['subproject'], ['id'])
    op.create_foreign_key(u'employees_ibfk_3', 'employees', 'projects', ['project'], ['id'])
    op.drop_column('employees', 'emp_subproject_id')
    op.drop_column('employees', 'emp_project_id')
    # ### end Alembic commands ###
