"""empty message

Revision ID: 6d4db65d9acd
Revises: 6e9f3bfd6169
Create Date: 2017-12-16 08:10:55.311940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d4db65d9acd'
down_revision = '6e9f3bfd6169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('project', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('subproject', sa.Integer(), nullable=False))
    op.drop_constraint(u'employees_ibfk_1', 'employees', type_='foreignkey')
    op.drop_constraint(u'employees_ibfk_3', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'projects', ['project'], ['id'])
    op.create_foreign_key(None, 'employees', 'subprojects', ['subproject'], ['id'])
    op.drop_column('employees', 'emp_subproject_id')
    op.drop_column('employees', 'emp_project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emp_project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('emp_subproject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(u'employees_ibfk_3', 'employees', 'subprojects', ['emp_subproject_id'], ['id'])
    op.create_foreign_key(u'employees_ibfk_1', 'employees', 'projects', ['emp_project_id'], ['id'])
    op.drop_column('employees', 'subproject')
    op.drop_column('employees', 'project')
    # ### end Alembic commands ###
