"""empty message

Revision ID: 6ecdff2e21f1
Revises: 5096d94850ad
Create Date: 2017-12-12 07:25:52.830870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecdff2e21f1'
down_revision = '5096d94850ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incentives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inc_employee_id', sa.Integer(), nullable=True),
    sa.Column('inc_subproject_id', sa.Integer(), nullable=True),
    sa.Column('inc_attendances_id', sa.Integer(), nullable=True),
    sa.Column('production', sa.Integer(), nullable=True),
    sa.Column('av_qa_score', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['inc_attendances_id'], ['attendances.id'], ),
    sa.ForeignKeyConstraint(['inc_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['inc_subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incentives')
    # ### end Alembic commands ###
