"""empty message

Revision ID: bd49dabd9a14
Revises: 4895dc4a3dc0
Create Date: 2017-12-16 20:34:06.438752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd49dabd9a14'
down_revision = '4895dc4a3dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emp_project_name', sa.String(length=60), nullable=False))
    op.add_column('employees', sa.Column('emp_role_name', sa.String(length=60), nullable=False))
    op.add_column('employees', sa.Column('emp_subproject_name', sa.String(length=60), nullable=False))
    op.drop_constraint(u'employees_ibfk_3', 'employees', type_='foreignkey')
    op.drop_constraint(u'employees_ibfk_2', 'employees', type_='foreignkey')
    op.drop_constraint(u'employees_ibfk_4', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'roles', ['emp_role_name'], ['name'])
    op.create_foreign_key(None, 'employees', 'projects', ['emp_project_name'], ['name'])
    op.create_foreign_key(None, 'employees', 'subprojects', ['emp_subproject_name'], ['name'])
    op.drop_column('employees', 'emp_role_id')
    op.drop_column('employees', 'emp_subproject_id')
    op.drop_column('employees', 'emp_project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emp_project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('emp_subproject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('emp_role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(u'employees_ibfk_4', 'employees', 'subprojects', ['emp_subproject_id'], ['id'])
    op.create_foreign_key(u'employees_ibfk_2', 'employees', 'roles', ['emp_role_id'], ['id'])
    op.create_foreign_key(u'employees_ibfk_3', 'employees', 'projects', ['emp_project_id'], ['id'])
    op.drop_column('employees', 'emp_subproject_name')
    op.drop_column('employees', 'emp_role_name')
    op.drop_column('employees', 'emp_project_name')
    # ### end Alembic commands ###
