"""empty message

Revision ID: d7afbca31f38
Revises: 08be3dc03508
Create Date: 2017-12-14 04:58:36.484992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7afbca31f38'
down_revision = '08be3dc03508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'projects_ibfk_1', 'projects', type_='foreignkey')
    op.drop_column('projects', 'pro_employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('pro_employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'projects_ibfk_1', 'projects', 'employees', ['pro_employee_id'], ['id'])
    # ### end Alembic commands ###
