"""empty message

Revision ID: f6784d83e37e
Revises: b0f199cab531
Create Date: 2017-12-11 09:39:00.455077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6784d83e37e'
down_revision = 'b0f199cab531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incentives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('attendances_id', sa.Integer(), nullable=True),
    sa.Column('production', sa.Integer(), nullable=True),
    sa.Column('av_qa_score', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attendances_id'], ['attendances.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incentives')
    # ### end Alembic commands ###
