"""empty message

Revision ID: fb7f25527787
Revises: 2220462d93e4
Create Date: 2017-12-12 07:21:25.321506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7f25527787'
down_revision = '2220462d93e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_number', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('emp_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('emp_project_id', sa.Integer(), nullable=True),
    sa.Column('emp_subproject_id', sa.Integer(), nullable=True),
    sa.Column('emp_role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emp_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['emp_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['emp_subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_emp_name'), 'employees', ['emp_name'], unique=False)
    op.create_index(op.f('ix_employees_emp_number'), 'employees', ['emp_number'], unique=True)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.add_column(u'projects', sa.Column('pro_employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'employees', ['pro_employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column(u'projects', 'pro_employee_id')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
